services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/sol_coffeesys:cached
    network_mode: service:db # DBと同じネットワークを共有
    # 開発を止めないための設定
    command: sleep infinity
    env_file:
      - ../.env

  db:
    image: postgres:17-trixie # 最新のポスグレ
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coffeesys_db
    ports:
      - "5432:5432"